### ISSUE TITLE
Background does not extend as list gets longer than 100% of view height

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/favlist.vue#13]

**Comment by spenserblack** [comment]
This should do it.
```css
#app {
  overflow: auto;
}
```
