### ISSUE TITLE
Allow YAML download

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/favlist.vue#85]
YAML file probably shouldn't be a 1:1 data format with the JSON :thinking: :shrug:

***

# Option 1

## Output as JSON

```json
{
  "favlists": [
    {
      "title": "numbers",
      "columns": ["odd", "even"],
      "data": [["1", "3"], ["2", "4"]]
    },
    {
      "title": "data formats",
      "columns": ["name", "supported"],
      "data": [["json", "yaml", "xml"], ["yes", "maybe", "no"]]
    }
  ]
}
```

## Output as YAML

```yaml
---
numbers:
  - odd: '1'
    even: '2'
  - odd: '3'
    even: '4'

data formats:
  - name: json
    supported: yes
  - name: yaml
    supported: maybe
  - name: xml
    supported: no
```
